### ISSUE TITLE
Change graph width

### ISSUE THREAD

**Issue by zywind** [takluyver/IRkernel#34]
Hi,

It's really nice that IRkernel lets you display graphs inline. But is there a way to change the display width and height?

**Comment by ihrke** [comment]
Hi, 

I made a work-around for that in my fork ihrke/IRkernel@32037a78360da110d80e41ed69c0b756adc4e872 where I created a global environment holding options that will be passed to the `png()` block.

You would use
~~~R
IRkernel::set_plot_options(width=900)
~~~
for changing and
~~~R
IRkernel::get_plot_options()
~~~
for inspecting it.

@takluyver is this of interest for the package? If so, I can set up a PR for that.

**Comment by takluyver** [comment]
Thanks Matthias! I like that approach, please do go ahead and make a pull
request.

**Comment by takluyver** [comment]
Merged @ihrke's changes, so you can now do e.g. `IRkernel::set_plot_options(width=900, height=900)`. See `?png` for the available options.
