### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by takluyver** [takluyver/IRkernel#5]
Handle a [complete_request](http://ipython.org/ipython-doc/dev/development/messaging.html#completion) to make tab completion work.

**Comment by ihrke** [comment]
Found this description of how to programmatically access R's tab-completion mechanism: twosigma/beaker-notebook#106.

Looks easy enough...

**Comment by takluyver** [comment]
Great, thanks.

For anyone looking to implement tab completion, I recommend that you now wait until IPython 3 is out. The completion messages underwent a significant refactor in the new message protocol (v5). Once IPython 3 is out with the new message spec, I'll drop support for msgspec v4 and completion can be written for the new spec.

**Comment by lucacerone** [comment]
Hi @takluyver and everybody, any idea whether tabcompletion can be tested at least experimentally
using IPython 3 (dev) and IRKernel? can you point me to some resource/project to try tabcompletion in a Jupyter R notebook?

**Comment by takluyver** [comment]
Do you mean to test using it, or to test implementing it? There's no tab completion implemented yet. The documentation here explains the protocol that will need to be used to handle completions:

http://ipython.org/ipython-doc/dev/development/messaging.html#completion

**Comment by lucacerone** [comment]
Thanks @takluyver , I am not much of a developer, but I'll go through it :) if I get to something I'll let you know

**Comment by rsmith31415** [comment]
Can we get an implementation of tab completion at this point? Ipython 3 is going to be released in a few days and it would be nice to test these kind of features in case there are bugs lurking around.

**Comment by rbirkelbach** [comment]
At this point, only the lack of having tab completion of some sort holds me back from using ipython/jupyter for my research. I would love to test use it.

**Comment by flying-sheep** [comment]
IPython 3 is out!

shouldn’t this be something like:

```r
handle_shell = function() {
   ...
   else if (msg$header$msg_type == "complete_request") {
      complete(msg)
   }
   ...
}

complete = function(request) {
    completions = with_top_env(userenv, {
        utils:::.assignLinebuffer(request$content$code)
        utils:::.assignEnd(request$content$cursor_pos - 1L)  #or not, or -2 or whatevs
        utils:::.guessTokenFromLine()
        utils:::.completeToken()
        utils:::.retrieveCompletions()
    })
    send_response("complete_reply", request, 'shell', list(
        matches = completions,  # supposed to be a list
        cursor_start : ???,
        cursor_end : ???,
        metadata : list(),  #that’s supposed to be a dict, dunno how that’s transformed
        status = 'ok'))
},
```

**Comment by takluyver** [comment]
Yes, something along those lines. I'll find time to update the communications to message spec 5, and then you're welcome to make a PR.

**Comment by flying-sheep** [comment]
is there a good testing workflow?

i.e.

1. upgrade installed version of IRKernel to your own updated copy of the dev version
2. restart the ipython/jupyter kernel using that updated version

---

besides, i need docs on how environments work here: where do variables get assigned to? why doesn’t `save.image()` work properly? and so on.

**Comment by takluyver** [comment]
- Testing workflow: yes, that's about it. You can install a local clone using `R CMD INSTALL IRkernel` (IRkernel being the directory where you have it cloned).
- Variables get assigned in an environment called `userenv` ([see here](https://github.com/takluyver/IRkernel/blob/master/R/execution.r#L141).
- `save.image()` - no idea. File a bug for it?

**Comment by virtualirfan** [comment]
Look forward to this. Our R developer is staying away from using this kernel mostly due to the better productivity in R console from tab completions :-(

**Comment by alvinwt** [comment]
Tab completion would be great with the R kernel. I have been developing a script in the IPython notebook before and I would love to do it in IPython 3.0 but I feel handicapped without the capabilities to complete file names and directories.

**Comment by flying-sheep** [comment]
fixed it, test plox:

```r
library(devtools)
install_github('flying-sheep/IRkernel', ref = 'autocompletion')
```
