### ISSUE TITLE
Output doesn't print immediately

### ISSUE THREAD

**Issue by cosinequanon** [takluyver/IRkernel#55]
I'm not sure what the root of the problem is but here is the minimal example I have:

    for (i in 1:5) {
        cat('=')
        Sys.sleep(.2)
    }

the above waits 1 second and then prints 5 equals signs. This is apposed to the following code:

    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)

that prints an equal sign every .2 seconds which is what I would expect from both examples. I played around with julia and python and they do what I expect in for loops.

FWIW I am running the ipython from master and R is version 3.1.2.

**Comment by takluyver** [comment]
I can reproduce this. I imagine it's something in the way the [evaluate](http://cran.rstudio.com/web/packages/evaluate/index.html) package works. You can see how we use it, creating an output handler with a `text` parameter, starting here: https://github.com/takluyver/IRkernel/blob/master/R/execution.r#L132

**Comment by cosinequanon** [comment]
Okay, thanks for pointing me to the code. It does seem like something internal to evaluate. For example:

    code1 <- "
    for (i in 1:5) {
        cat('=')
        Sys.sleep(.2)
    }"
    length(evaluate(code1)) # this is 2

    code2 <- "
    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)
    cat('=')
    Sys.sleep(.2)"
    length(evaluate(code2)) $ this is 15

If we use eval we get the desired effect:

    # the following 2 lines produce identical results
    eval(parse(text=code1))
    eval(parse(text=code2))

Unfortunately, I looked through the docs and code of `evaluate` and I couldn't find anything to change this behavior

**Comment by takluyver** [comment]
I was originally doing a plain eval, but getting all the output capturing
was a pain, and evaluate takes care of that in a fairly neat way.

You could try filling an issue against evaluate for this. I can help make a
minimal test case showing the issue. But it's possible that the developers
don't consider it important.

**Comment by cosinequanon** [comment]
Yes, I can definitely see the need for evaluate over eval. I'd love to get this fixed though and can file an issue for the evaluate package, but before I do, what did you have in mind for a "minimal test case showing the issue." How would it be different than what I initially posted?

**Comment by takluyver** [comment]
I misunderstood what the length() of evaluate output meant - that snippet should work as a minimal test case. I was trying to make it actually show the same behaviour (printing all at once versus printing bit by bit) outside the IPython machinery, but I can't get it to print anything live in the terminal.

**Comment by takluyver** [comment]
I'd forgotten that this was already tracked as #3. There's useful info on both - I'm choosing this one to close, pretty arbitrarily.
