### ISSUE TITLE
Difference of behaviour for "substitute" between R shell and Jupyter R notebook.

### ISSUE THREAD

**Issue by lucacerone** [takluyver/IRkernel#57]
The command `substitute` does not behave in the same way in a normal R shell and in a Jupyter notebook.

For example:

```
x <- 5
substitute(y + x)
```
returns `y + x` in an R shell, but `y + 5`  in an R notebook.

This is probably due to the fact that the environment in an R notebook is not the R_GlobalEnv.

This could cause some issues when NSE is involved.

**Comment by takluyver** [comment]
Looks like the global env is the culprit - the docs say:

> If it is an ordinary variable, its value is substituted, unless ‘env’ is ‘.GlobalEnv’ in which case the symbol is left unchanged.

What is NSE?

**Comment by lucacerone** [comment]
NSE stands for Non Standard Evaluation, which is explained quite well (and much better than I would be able to do) here: http://adv-r.had.co.nz/Computing-on-the-language.html

Mind if people works well with environments, this should not be an issue (but sometimes, authors just assign variables to .GlobalEnv, rather than following the hierarchy properly).
In this case you might have that functions and scripts that work well in R wouldn't work in a notebook (but it is because they are buggy in the first place).

I have marked it as a bug, because I assume one would want to have exactly the same behaviour in a notebook and in an R shell; but probably it is just enough to be aware than when working in an R notebook one is not working in the .GlobalEnv...

**Comment by takluyver** [comment]
#71 should fix this.

**Comment by takluyver** [comment]
I'm optimistically closing this as I merged #71. If it's still a problem, we can reopen it.
