### ISSUE TITLE
save.image doesn’t work

### ISSUE THREAD

**Issue by flying-sheep** [takluyver/IRkernel#61]
it doesn’t save everything. the docs say it’s the same as

```r
save(list = ls(all.names = TRUE), file = ".RData", envir = .GlobalEnv)
```

something here goes wrong. is it `.GlobalEnv` or `ls()`?

**Comment by takluyver** [comment]
.globalenv - IRkernel does not run your code in the global environment.
Sadly, a few things seem to assume that end user code always is run in the
global env.

**Comment by flying-sheep** [comment]
that’s because it’s [supposed to be](https://stat.ethz.ch/R-manual/R-devel/library/base/html/environment.html):

> The global environment `.GlobalEnv`, **more often known as the user's workspace**, is the first item on the search path. It can also be accessed by `globalenv()`. On the search path, each item's enclosure is the next item.

(emphasis mine)

**Comment by flying-sheep** [comment]
i tested this and it works!

hacky as hell though.
