### ISSUE TITLE
Testing the new autocompletion

### ISSUE THREAD

**Issue by rsmith31415** [takluyver/IRkernel#66]
I tried to test the new autocompletion feature, but I wasn't able to obtain good results.

I (re)installed according to the README (maybe here is when I broke my installation):

    # Need RCurl for install_github
    install.packages('RCurl')
    library(devtools)
    install_github('armstrtw/rzmq')
    install_github("takluyver/IRdisplay")
    install_github("takluyver/IRkernel")

    # Only if you have IPython 3 or above installed:
    IRkernel::installspec()

And after opening a notebook, I got this:

![screenshot from 2015-03-13 18 43 43](https://cloud.githubusercontent.com/assets/599274/6649497/295aed78-c9b1-11e4-8046-f9a0cd64f4f1.png)

And some errors in the console:

     [I 18:43:34.578 NotebookApp] Adapting to protocol v4.0 for kernel 2da601ae-8408-4be6-b6e3-b61743ed876c
     [1] "Got unhandled msg_type:" "object_info_request"  

If a type `ta` or `data.` and hit Tab, then I get good results. 

By the way, are we going to get tooltips as part of the implementation? Because right now Shift-Tab has no effect.

**Comment by takluyver** [comment]
Ping @flying-sheep , can you take a look?

Tooltips are a separate feature from tab completion - someone would have to write that separately.

**Comment by flying-sheep** [comment]
ah, interesting.

IPython interprets `<identifier>.<identifier><tabpress>` as object introspection request.

you know, because almost all languages use dots as division between object and a property of the object.

but R has uncommon identifiers which may include dots. (and, unlike e.g. JS, no dollar signs)

ideally, we’d convince IPython to interpret `[\w_.][\w_.\d]*` (or similar, we’ll have to look up the correct regex) as `<identifier>` and `<identifier>[@$]<identifier><tabpress>` as introspection r

anyone an idea how?

**Comment by takluyver** [comment]
I'm not sure why it's making an introspection request, but there is some Python syntax specificity when using msgspec 4. This was the main reason we made msgspec 5 - now we just pass back the whole cell and let the kernel figure out what's relevant for completions. So it sounds like we need to switch to the new version of the msg spec. I'll try to work on that this weekend.

**Comment by flying-sheep** [comment]
> I'm not sure why it's making an introspection request

didn’t i explain that? or was a wrong?

in most languages other than R, `foo.bar` means “get the `bar` property of `foo`”. i’m guessing that’s why IPython tries to introspect the (probably nonexistent) `foo` object.

---

[here](http://stackoverflow.com/questions/29049126/what-constitutes-a-valid-symbol-identifier-in-r/29049170#29049170) someone told me/us what a identifier actually is, if we still need that after all

**Comment by takluyver** [comment]
I got that, but I didn't think the frontend works like that, even for msgspec 4. It will try to tokenise and send back the relevant token for the kernel, which in this case would be `foo.bar`, and then the kernel would introspect `foo` to see what attributes it has. Maybe there's something about the msgspec adapter that I've forgotten.

**Comment by flying-sheep** [comment]
> It will try to tokenise and send back the relevant token for the kernel, which in this case would be foo.bar, and then the kernel would introspect foo to see what attributes it has.

wait, so at which point will the token and cursor position be translated to a request and by what?

kernel or frontend?

**Comment by takluyver** [comment]
In IPython 2, the frontend tokenises it (roughly - in the notebook this was just a regex) and sends the completion request with what it thinks is the current token.

In IPython 3, with msgspec 5, the frontend sends the whole cell. But the *server* knows how to adapt between msgspec 4 and 5, so if the kernel says it's using msgspec 4, the server will tokenise the code and attempt to send it just the current token. Once IRkernel says that it speaks msgspec 5, it will get the whole cell with no tokenisation done.

**Comment by flying-sheep** [comment]
and what message is then sent if the frontend doesn’t tokenize anymore?

**Comment by takluyver** [comment]
The frontend sends a msgspec 5 completion request, which contains the whole cell of code and the cursor position within that: http://ipython.org/ipython-doc/dev/development/messaging.html#completion

**Comment by flying-sheep** [comment]
but [`inspect_request`](http://ipython.org/ipython-doc/dev/development/messaging.html#introspection) still exists. when is it sent then?

**Comment by takluyver** [comment]
The notebook sends `inspect_request` when you press shift-tab to get information tooltips.

**Comment by flying-sheep** [comment]
ah, so the problem with the single characters in the screenshot isn’t the `object_info_request`?

in this case, it looks like a single string is produced and then displayed as list of results. if that’s right then the problem is probably in the marshalling.

my theory: a single R string (aka a length-1 character vector in R lingo) is converted to a single python string and passed to a function that expects an iterable of completion results. since strings in python are iterable, the string gets interpreted as list of results, each of which is one character.

**Comment by takluyver** [comment]
Yes, I think this is down to the way R only has length 1 vectors. That means that when we serialise to JSON, we can't distinguish a string from a list of strings with only one element. The calls to `toJSON` use `auto_unbox=TRUE`, which will treat length-1 vectors of strings as single strings.

**Comment by flying-sheep** [comment]
could we instead use `unbox()` where appropriate?

**Comment by takluyver** [comment]
Careful use of `unbox()` might make sense as the R kernel expands, though thanks for fixing completions in the meantime.
