### ISSUE TITLE
Problem on Windows with R objects

### ISSUE THREAD

**Issue by DSfrmBkln** [takluyver/IRkernel#67]
Hi I've installed IRkernel using bits and pieces I've found here and there, and I seem to have hit a snag.  Before I describe the problem in detail, a little background.  I run windows, which I know makes this harder.  In particular, I built rzmq for windows using this guide:

http://blogs.msdn.com/b/gpalem/archive/2013/02/06/building-zeromq-for-r-rzmq-with-visual-studio-express-full.aspx

and got around another problem using this tip:

http://ihrke.github.io/jupyter.html

So far, things seem to work fine except for one issue: opening an iPython notebook and choosing an 'R' kernal, I run ```library("vars")```, load some data (```my_data```), and then I run ```test <- ur.df(my_data, type = "trend", lags = 2)```.  When I run ```test```, I get, as expected

```
############################################################### 
# Augmented Dickey-Fuller Test Unit Root / Cointegration Test # 
############################################################### 

The value of the test statistic is: -7.9808 
```

However, when I run ```summary(test)```

I get

```
Length  Class   Mode 
     1  ur.df     S4 
```

I should be getting a far more detailed result regarding the Dickey-Fuller unit root test.  Digging a little further, I tried
```
class(test)
```
and got
```
[1] "ur.df"
attr(,"package")
[1] "urca"
```
and ```class(summary(test))``` gives me
```
[1] "summaryDefault" "table"  
```
(I believe it should be in the class ```sumurca``` according to the documentation for the packages ```vars``` and ```urca```)

Also, ```showMethods("summary")``` gives
```
Function: summary (package base)
object="ANY"
object="ca.jo"
object="ca.po"
object="cajo.test"
object="lm"
    (inherited from: object="ANY")
object="ur.df"
object="ur.ers"
object="ur.kpss"
object="ur.pp"
object="ur.sp"
object="ur.za"
```
When I try any of this in the command line R (or Rgui), it works as expected.  Any idea what's going on?  As you may have noticed, I'm no expert on any of this, but I've done a fair bit of googling, and I'm stumped.  I also have no idea if this is unique to one package.

My setup is windows 7 (64-bit), R 3.1.2, iPython 3.  I'm sure there is some other info you need to make a sensible recommendation and, given some guidance, I'm happy to provided it.  Running ```sessionInfo()```, I get

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vars_1.5-2        lmtest_0.9-33     urca_1.2-8        strucchange_1.5-0
[5] sandwich_2.3-2    zoo_1.7-11        MASS_7.3-39      

loaded via a namespace (and not attached):
 [1] base64_1.1      digest_0.6.8    evaluate_0.5.5  grid_3.1.2     
 [5] IRdisplay_0.1   IRkernel_0.2    jsonlite_0.9.14 lattice_0.20-30
 [9] rzmq_0.7.7      stringr_0.6.2   uuid_0.1-1     
```

Thank you for any thoughts.

Cheers,

DS

**Comment by takluyver** [comment]
Most problems with code running differently in IRkernel seem to come down to things that assume they're in the global environment - I hadn't realised how problematic running in another environment would be when I started writing that. I will try to fix it.

**Comment by DSfrmBkln** [comment]
Thank you for looking into it.  I'm happy to provide more information if it helps.

**Comment by takluyver** [comment]
Can you test #71 to see if it fixes this? You should be able to do `devtools::install_github('takluyver/IRkernel#71'`

**Comment by DSfrmBkln** [comment]
Bingo!  Seems to work on the example I supplied.  I'll let you know how it goes from here forward.  Thank you!

**Comment by takluyver** [comment]
Thanks for checking! I've merged that fix.
