### ISSUE TITLE
Package caret doesn't run in the notebook

### ISSUE THREAD

**Issue by elyase** [takluyver/IRkernel#70]
The following code runs ok in the command line but not in the notebook:
```
library(caret)
data(iris)
model <- train(Species~., data=iris, method="nb")
```

On the notebook it fails with:
```
Error in frameTypes(env): not a proper evaluation environment
```

**Comment by takluyver** [comment]
Can you try out #71?

**Comment by takluyver** [comment]
It should be `devtools::install_github('takluyver/IRkernel#71')` to install from that branch.

**Comment by elyase** [comment]
Yes, it is working now thanks. But now the kernel dies anytime I want to autocomplete with <Tab>. If I revert the change autocompletion starts working ok again.

**Comment by takluyver** [comment]
Thanks for catching that, should be fixed now.

**Comment by elyase** [comment]
Looks great now, thanks for the quick fix!

**Comment by takluyver** [comment]
That's really your good fortune - several people have reported bugs where code doesn't run as expected, and I hope this will fix all of them. You happened to report one just before I got round to fixing it ;-)
